networks:
  unimate-net:
    name: unimate-network

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - unimate-net
  rag-service:
    container_name: rag-service
    build:
      context: .
      dockerfile: Dockerfile.rag
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - /home/unimate/chroma_db:/home/unimate/chroma_db  # Mount EXISTING directory
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - unimate-net

volumes:
  ollama_data:
