FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip3 install --retries 5 --timeout 1000 langchain langchain-community langchain-core  chromadb sentence-transformers

# Copy code
COPY apps/qa-engine/ragEngine.py . 


# NO mkdir command here - we'll mount the existing directory
CMD ["python", "ragEngine.py", "What is this document about?", "--host", "http://ollama:11434"]
